Auto commit the init results if successful
When export, export from the child of this auto commit.

diff --git a/bin/inspurcommit b/bin/inspurcommit
--- a/bin/inspurcommit
+++ b/bin/inspurcommit
@@ -117,16 +117,18 @@ Export(){
     local currhash
     local chfn
     local fci
+    local fcic
     local mode
     local ch_content
     FindFile "$fci_file_name" || return
     fci=$(cat "$fci_file_name")
+    fcic=$(git rev-list --reverse "$fci"..@ | head -1)
     if [ "$1" == "none" ] || [ ! "$1" ]; then
         mode="all"
-        ch_content=$(git log "$fci".. --format="%b" | sed '/^Change-Id:\s\w\{41\}$/,+1d')
+        ch_content=$(git log "$fcic".. --format="%b" | sed '/^Change-Id:\s\w\{41\}$/,+1d')
     else
         mode="notall"
-        ch_content=$(git log $(cat "$fci_file_name").. --format="%b" | grep -v "^$1:" | sed '/^Change-Id:\s\w\{41\}$/,+1d')
+        ch_content=$(git log "$fcic".. --format="%b" | grep -v "^$1:" | sed '/^Change-Id:\s\w\{41\}$/,+1d')
     fi
     if [ ! "$ch_content" ]; then
         >&2 echo "${cRed}ERROR: Nothing to export.$cSuf"
@@ -217,13 +219,20 @@ case "$op" in
                 exit 1
                 ;;
         esac
+        if CheckStage 2>/dev/null
+        then
+            >&2 echo "${cRed}ERROR: Please commit or stash your staged changes before init.$cSuf"
+            >&2 git status
+            exit 1
+        fi
         git log --format="%H" -1 > "$fci_file_name" && \
             cp $(dirname "$0")/"$template_file_name" ./ && \
             echo "/ChangeHistory-*.txt" >> .gitignore && \
             git add "$template_file_name" "$fci_file_name" .gitignore && \
-            echo "${cGrn}Initialization completed successfully.$cSuf
-You can fill the change history template now and commit this initialization
-using command 'inspurcommit', or commit it along with next code changes."
+            git commit -m "INSPURCOMMIT-INIT" -m "
+This commit was automatically generated to initialize this repository in
+order to use Inspur Commit Kit." 1>/dev/null && \
+            echo "${cGrn}Initialization completed successfully.$cSuf"
         ;;
     *)
         >&2 echo "${cRed}ERROR: Invalid option - $1$cSuf"
