Add colors to prompts

diff --git a/bin/inspurcommit b/bin/inspurcommit
--- a/bin/inspurcommit
+++ b/bin/inspurcommit
@@ -15,7 +15,7 @@ Options:
 ValidateTemplate(){
     if [ ! -e "$tempFn" ]
     then
-        echo "ERROR: Couldn't find template file $tempFn" >&2
+        >&2 echo "${cRed}ERROR: Couldn't find template file $tempFn.$cSuf"
         exit 2
     fi
 }
@@ -24,7 +24,7 @@ ValidateJgn(){
     which $jgn 1>/dev/null 2>&1
     if [ $? -ne 0 ]
     then
-        echo "ERROR: Coundn't find $jgn." >&2
+        echo "${cRed}ERROR: Coundn't find $jgn.$cSuf" >&2
         exit 3
     fi
 }
@@ -32,7 +32,7 @@ ValidateJgn(){
 ValidateHistoryField(){
     local value=$(cat "$tempFn" | grep "^$1:" | sed "s/^$1:\s*//")
     [ -z "$value" ] || return 0
-    >&2 echo "ERROR: Field '$1' is empty."
+    >&2 echo "${cRed}ERROR: Field '$1' is empty.$cSuf"
     return 1
 }
 
@@ -57,7 +57,7 @@ ValidateHistory(){
     ValidateHistoryField 'Solution'
     let errors+=$?
     [ $errors -gt 0 ] || return 0
-    >&2 echo "ERROR: Change history is not completed."
+    >&2 echo "${cRed}ERROR: Change history is not completed.$cSuf"
     exit 1
 }
 
@@ -65,26 +65,25 @@ CheckStage(){
     local diffname=$(git diff --cached --name-only)
     case "$diffname" in
         "")
-            >&2 echo "ERROR: There is no staged changes."
-            >&2 echo "Stage changes to be committed with 'git add'."
+            >&2 echo "${cRed}ERROR: There is no staged changes.
+Stage changes to be committed with 'git add'.$cSuf"
             exit 1
             ;;
         *"$template_file_name"*)
             [ "$1" == "template" ] && return 0
             if ! FindFile "$fci_file_name" 2>/dev/null
             then
-                >&2 echo "
-ERROR: It seems that you haven't initialize this repository.
+                >&2 echo "${cRed}ERROR: It seems that you haven't initialize this repository.
 Checkout the last commit that ARN'T commit with inspurcommit and use
-command 'inspurcommit init'."
+command 'inspurcommit init'.$cSuf"
                 exit 1
             elif [ $(git log -1 --format="%H") == $(cat "$fci_file_name") ]
             then
                 return 0
             fi
             git restore --staged "$template_file_name" > /dev/null
-            >&2 echo "Warning: $template_file_name was staged. But was skipped."
-            >&2 echo "If you intend to modify the template, use command 'inspurcommit template'."
+            >&2 echo "${cYlw}Warning: $template_file_name was staged. But was skipped.
+If you intend to modify the template, use command 'inspurcommit template'.$cSuf"
             CheckStage
             return 1
             ;;
@@ -94,14 +93,14 @@ command 'inspurcommit init'."
 CheckFileAlreadyExists(){
     local filename="$1"
     [ -e "$filename" ] || return 0
-    >&2 echo "ERROR: File $filename already exists."
+    >&2 echo "${cRed}ERROR: File $filename already exists.$cSuf"
     return 1
 }
 
 FindFile(){
     local filename="$1"
     [ -e "$filename" ] && return 0
-    >&2 echo "ERROR: Couldn't find file $filename."
+    >&2 echo "${cRed}ERROR: Couldn't find file $filename.$cSuf"
     return 1
 }
 
@@ -143,7 +142,7 @@ Export(){
         ch_content=$(git log $(cat "$fci_file_name").. --format="%b" | grep -v "^$1:" | sed '/^Change-Id:\s\w\{41\}$/,+1d')
     fi
     if [ ! "$ch_content" ]; then
-        >&2 echo "ERROR: Nothing to export."
+        >&2 echo "${cRed}ERROR: Nothing to export.$cSuf"
         return 1
     fi
     currhash=$(git log -1 --format='%h')
@@ -164,9 +163,9 @@ Export(){
 }
 
 DebugReport(){
-    >&2 echo "Warning: $1"
-    >&2 echo "You've just met a debug warning."
-    >&2 echo "If it's not inconvenient, please contact $author on this issue, or create an issue on $issuelink. Thanks!"
+    >&2 echo "${cYlw}Warning: $1
+You've just met a debug warning.
+If it's not inconvenient, please contact $author on this issue, or create an issue on $issuelink. Thanks!$cSuf"
 }
 
 declare -r rev='0.1.0'
@@ -175,6 +174,10 @@ declare -r author='Johnny Appleseed <liuzhaohui@inspur.com>'
 declare -r issuelink='https://github.com/islzh/jg/issues/new'
 declare -r jgn="jgnumberforthehistory"
 declare -r tempFn=$template_file_name
+declare -r cRed="[91m"
+declare -r cGrn="[92m"
+declare -r cYlw="[93m"
+declare -r cSuf="[0m"
 
 declare -r op="${1,,}"
 case "$op" in
@@ -211,10 +214,10 @@ case "$op" in
         CheckFileAlreadyExists "$fci_file_name" || exit
         git log --format="%H" -1 > "$fci_file_name" && \
             git add "$fci_file_name" && \
-            echo "Complete."
+            echo "${cGrn}Complete.$cSuf"
         ;;
     *)
-        >&2 echo "ERROR: Invalid option - $1"
+        >&2 echo "${cRed}ERROR: Invalid option - $1$cSuf"
         >&2 ShowUsage
         exit 1
         ;;
