Implement change-id filter and farewell commit id
Every project has an unique farewell commit id, so instead of defining a
variable or constant, read it from file $fci_file_name in project folder.

diff --git a/bin/inspurcommit b/bin/inspurcommit
--- a/bin/inspurcommit
+++ b/bin/inspurcommit
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-declare -r template_file_name=ChangeHistoryTemplate.txt
-declare -r independence_day="Jul 14 0:00:00 2021 +0800"
-declare -r change_history_format="%b"
+declare -r template_file_name="ChangeHistoryTemplate.txt"
+declare -r fci_file_name="farewell-commit-id"
 
 ShowUsage(){
     echo "
@@ -47,10 +46,17 @@ CheckStage(){
     esac
 }
 
-CheckFileExistence(){
+CheckFileAlreadyExists(){
     local filename="$1"
     [ -e $filename ] || return 0
     >&2 echo "inspurcommit: ERROR: File $filename already exists."
+    return 1
+}
+
+FindFile(){
+    local filename="$1"
+    [ -e $filename ] && return 0
+    >&2 echo "inspurcommit: ERROR: Couldn't find file $filename."
     return 1
 }
 
@@ -97,15 +103,17 @@ case "${1,,}" in
         ;;
     "export")
         echo
+        FindFile "$fci_file_name" || exit
         historyFn=${2:-"./ChangeHistory.txt"}
-        CheckFileExistence "$historyFn" || exit
-        git log --since="$independence_day" --format="$change_history_format" | grep -vP '^Scope:' > $historyFn
+        CheckFileAlreadyExists "$historyFn" || exit
+        git log "$(cat $fci_file_name)".. --format="%b" | grep -vP '^Scope:' | vim -es '+%s/\C\nChange-Id:\s\w\{41}\n//ge' '+%print' '+q!' /dev/stdin > $historyFn
         ;;
     "exportall")
         echo
+        FindFile "$fci_file_name" || exit
         historyFn=${2:-"./ChangeHistory.txt"}
-        CheckFileExistence "$historyFn" || exit
-        git log --since="$independence_day" --format="$change_history_format" > $historyFn
+        CheckFileAlreadyExists "$historyFn" || exit
+        git log "$(cat $fci_file_name)".. --format="%b" | vim -es '+%s/\C\nChange-Id:\s\w\{41}\n//ge' '+%print' '+q!' /dev/stdin > $historyFn
         ;;
     "template")
         echo
