Remove 'inspurcommit' from error prompts
It is unncessary but takes a 14-char space.

diff --git a/bin/inspurcommit b/bin/inspurcommit
--- a/bin/inspurcommit
+++ b/bin/inspurcommit
@@ -15,7 +15,7 @@ Options:
 ValidateTemplate(){
     if [ ! -e $tempFn ]
     then
-        echo "inspurcommit: ERROR: Couldn't find template file $tempFn" >&2
+        echo "ERROR: Couldn't find template file $tempFn" >&2
         exit 2
     fi
 }
@@ -24,7 +24,7 @@ ValidateJgn(){
     which $jgn 1>/dev/null 2>&1
     if [ $? -ne 0 ]
     then
-        echo "inspurcommit: ERROR: Coundn't find $jgn." >&2
+        echo "ERROR: Coundn't find $jgn." >&2
         exit 3
     fi
 }
@@ -32,7 +32,7 @@ ValidateJgn(){
 ValidateHistoryField(){
     local value=$(cat $tempFn | grep "^$1:" | sed "s/^$1:\s*//")
     [ -z "$value" ] || return 0
-    >&2 echo "inspurcommit: ERROR: Field '$1' is empty."
+    >&2 echo "ERROR: Field '$1' is empty."
     return 1
 }
 
@@ -57,7 +57,7 @@ ValidateHistory(){
     ValidateHistoryField 'Solution'
     let errors+=$?
     [ $errors -gt 0 ] || return 0
-    >&2 echo "inspurcommit: ERROR: Change history is not completed."
+    >&2 echo "ERROR: Change history is not completed."
     exit 1
 }
 
@@ -65,14 +65,14 @@ CheckStage(){
     local diffname=$(git diff --cached --name-only)
     case "$diffname" in
         "")
-            >&2 echo "inspurcommit: ERROR: There is no staged changes."
+            >&2 echo "ERROR: There is no staged changes."
             >&2 echo "Stage changes to be committed with 'git add'."
             exit 1
             ;;
         *"$template_file_name"*)
             [ "$1" == "template" ] && return 0
             git restore --staged "$template_file_name" > /dev/null
-            >&2 echo "inspurcommit: Warning: $template_file_name was staged. But was skipped."
+            >&2 echo "Warning: $template_file_name was staged. But was skipped."
             >&2 echo "If you intend to modify the template, use command 'inspurcommit template'."
             CheckStage
             return 1
@@ -83,14 +83,14 @@ CheckStage(){
 CheckFileAlreadyExists(){
     local filename="$1"
     [ -e $filename ] || return 0
-    >&2 echo "inspurcommit: ERROR: File $filename already exists."
+    >&2 echo "ERROR: File $filename already exists."
     return 1
 }
 
 FindFile(){
     local filename="$1"
     [ -e $filename ] && return 0
-    >&2 echo "inspurcommit: ERROR: Couldn't find file $filename."
+    >&2 echo "ERROR: Couldn't find file $filename."
     return 1
 }
 
@@ -116,7 +116,7 @@ Export(){
         ch_content=$(git log $(cat $fci_file_name).. --format="%b" | grep -v "^$1:" | sed '/^Change-Id:\s\w\{41\}$/,+1d')
     fi
     if [ ! "$ch_content" ]; then
-        >&2 echo "inspurcommit: ERROR: Nothing to export."
+        >&2 echo "ERROR: Nothing to export."
         return 1
     fi
     CheckFileAlreadyExists "$chfn" || return
@@ -165,7 +165,7 @@ case "${1,,}" in
         git log --format="%H" -1 > "$fci_file_name" && echo "Complete."
         ;;
     *)
-        >&2 echo "inspurcommit: ERROR: Invalid option - $1"
+        >&2 echo "ERROR: Invalid option - $1"
         >&2 ShowUsage
         exit 1
         ;;
