Exit when any validate history field fails
List all empty fields will spend extra time and is not necessary, which
is a common case when people press Ctrl+c.

diff --git a/bin/inspurcommit b/bin/inspurcommit
--- a/bin/inspurcommit
+++ b/bin/inspurcommit
@@ -32,33 +32,20 @@ ValidateJgn(){
 ValidateHistoryField(){
     local value=$(cat "$tempFn" | grep "^$1:" | sed "s/^$1:\s*//")
     [ -z "$value" ] || return 0
-    >&2 echo "${cRed}ERROR: Field '$1' is empty.$cSuf"
+    >&2 echo "${cRed}ERROR: Field '$1' of change history is empty.$cSuf"
     return 1
 }
 
 ValidateHistory(){
-    local errors=0
-    ValidateHistoryField 'Tag#'
-    let errors+=$?
-    ValidateHistoryField 'Label#'
-    let errors+=$?
-    ValidateHistoryField 'Issue#'
-    let errors+=$?
-    ValidateHistoryField 'Scope'
-    let errors+=$?
-    ValidateHistoryField 'Severity'
-    let errors+=$?
-    ValidateHistoryField 'Category'
-    let errors+=$?
-    ValidateHistoryField 'Symptom'
-    let errors+=$?
-    ValidateHistoryField 'RootCause'
-    let errors+=$?
-    ValidateHistoryField 'Solution'
-    let errors+=$?
-    [ $errors -gt 0 ] || return 0
-    >&2 echo "${cRed}ERROR: Change history is not completed.$cSuf"
-    exit 1
+    ValidateHistoryField 'Tag#' || exit
+    ValidateHistoryField 'Label#' || exit
+    ValidateHistoryField 'Issue#' || exit
+    ValidateHistoryField 'Scope' || exit
+    ValidateHistoryField 'Severity' || exit
+    ValidateHistoryField 'Category' || exit
+    ValidateHistoryField 'Symptom' || exit
+    ValidateHistoryField 'RootCause' || exit
+    ValidateHistoryField 'Solution' || exit
 }
 
 CheckStage(){
